import os

ROOT_DIR = os.path.dirname(os.path.abspath(os.path.join(__file__, os.pardir)))
ACT_KEY = "actuator_obs"
OBJ_KEY = "object_obs"
GOAL_KEY = "goal_obs"
POSITIONS_KEY = "positions"

POSE_INFO_KEYS = {
    "pose",
    "bonus",
    "penalty",
    "act_reg",
    "done",
    "solved",
    "sparse",
}

REACH_INFO_KEYS = {
    "reach",
    "bonus",
    "penalty",
    "act_reg",
    "done",
    "solved",
    "sparse",
}

BAODING_INFO_KEYS = {
    "pos_dist_1",
    "pos_dist_2",
    "act_reg",
    "alive",
    "solved",
}

REORIENT_INFO_KEYS = {
    "pos_dist",
    "rot_dist",
    "pos_dist_diff",
    "rot_dist_diff",
    "act_reg",
    "alive",
    "solved",
}

WALK_INFO_KEYS = {
    "done",
    "solved",
    "sparse",
    "vel_reward",
    "cyclic_hip",
    "ref_rot",
    "joint_angle_rew",
    "act_reg",
}

CHASETAG_INFO_KEYS = {
    "done",
    "solved",
    "sparse",
    "vel_reward",
    "cyclic_hip",
    "ref_rot",
    "joint_angle_rew",
    "act_reg",
    "distance",
    "alive",
    "lose",
}

ISAAC_REACH_INFO_KEYS = {
}

ENV_INFO = {
    "MuscleElbowPoseFixed": POSE_INFO_KEYS,
    "MuscleElbowPoseRandom": POSE_INFO_KEYS,
    "MuscleFingerPoseFixed": POSE_INFO_KEYS,
    "MuscleFingerPoseRandom": POSE_INFO_KEYS,
    "MuscleHandPoseFixed": POSE_INFO_KEYS,
    "MuscleHandPoseRandom": POSE_INFO_KEYS,
    "MuscleHandPoseRandomHalfRange": POSE_INFO_KEYS,
    "MuscleFingerReachFixed": REACH_INFO_KEYS,
    "MuscleFingerReachRandom": REACH_INFO_KEYS,
    "MuscleHandReachFixed": REACH_INFO_KEYS,
    "MuscleHandReachRandom": REACH_INFO_KEYS,
    "MuscleBaodingEnvP0": BAODING_INFO_KEYS,
    "MuscleBaodingEnvP1": BAODING_INFO_KEYS,
    "MuscleBaodingEnvP2": BAODING_INFO_KEYS,
    "MuscleBaodingEnvP3": BAODING_INFO_KEYS,
    "MuscleReorientEnvP0": REORIENT_INFO_KEYS,
    "MuscleReorientEnvP1": REORIENT_INFO_KEYS,
    "MuscleReorientEnvP2": REORIENT_INFO_KEYS,
    "IsaacgymHandReach": ISAAC_REACH_INFO_KEYS,
    "IsaacgymFingerReach": ISAAC_REACH_INFO_KEYS,
    "IsaacgymReorient": ISAAC_REACH_INFO_KEYS,
    "MuscleLegsStandEnv": REACH_INFO_KEYS,
    "MuscleLegsWalkEnv": WALK_INFO_KEYS,
    "CustomChaseTag": CHASETAG_INFO_KEYS
}

OBS_ID_MAP = {
    "extn": 0,  # Finger muscles
    "adabR": 1,
    "adabL": 2,
    "mflx": 3,
    "dflx": 4,
    "IFadb": 5,  # Finger joints
    "IFmcp": 6,
    "IFpip": 7,
    "IFdip": 8,
    "TRIlong": 9,  # Elbow muscles
    "TRIlat": 10,
    "TRImed": 11,
    "BIClong": 12,
    "BICshort": 13,
    "BRA": 14,
    "r_elbow_flex": 15,  # Elbow joint
    "ECRL": 16,  # Hand muscles
    "ECRB": 17,
    "ECU": 18,
    "FCR": 19,
    "FCU": 20,
    "PL": 21,
    "PT": 22,
    "PQ": 23,
    "FDS5": 24,
    "FDS4": 25,
    "FDS3": 26,
    "FDS2": 27,
    "FDP5": 28,
    "FDP4": 29,
    "FDP3": 30,
    "FDP2": 31,
    "EDC5": 32,
    "EDC4": 33,
    "EDC3": 34,
    "EDC2": 35,
    "EDM": 36,
    "EIP": 37,
    "EPL": 38,
    "EPB": 39,
    "FPL": 40,
    "APL": 41,
    "OP": 42,
    "RI2": 43,
    "LU_RB2": 44,
    "UI_UB2": 45,
    "RI3": 46,
    "LU_RB3": 47,
    "UI_UB3": 48,
    "RI4": 49,
    "LU_RB4": 50,
    "UI_UB4": 51,
    "RI5": 52,
    "LU_RB5": 53,
    "UI_UB5": 54,
    "pro_sup": 55,  # Hand joints
    "deviation": 56,
    "flexion": 57,
    "cmc_abduction": 58,
    "cmc_flexion": 59,
    "mp_flexion": 60,
    "ip_flexion": 61,
    "mcp2_flexion": 62,
    "mcp2_abduction": 63,
    "pm2_flexion": 64,
    "md2_flexion": 65,
    "mcp3_flexion": 66,
    "mcp3_abduction": 67,
    "pm3_flexion": 68,
    "md3_flexion": 69,
    "mcp4_flexion": 70,
    "mcp4_abduction": 71,
    "pm4_flexion": 72,
    "md4_flexion": 73,
    "mcp5_flexion": 74,
    "mcp5_abduction": 75,
    "pm5_flexion": 76,
    "md5_flexion": 77,
    "THtip_x": 78,  # Hand reach targets
    "THtip_y": 79,
    "THtip_z": 80,
    "IFtip_x": 81,  # This is also shared with finger reach
    "IFtip_y": 82,
    "IFtip_z": 83,
    "MFtip_x": 84,
    "MFtip_y": 85,
    "MFtip_z": 86,
    "RFtip_x": 87,
    "RFtip_y": 88,
    "RFtip_z": 89,
    "LFtip_x": 90,
    "LFtip_y": 91,
    "LFtip_z": 92,
    "ball1": 93,  # baoding objects
    "ball2": 94,
    "obj1_target_pos_x": 95,  # Generic object position goals
    "obj1_target_pos_y": 96,
    "obj1_target_pos_z": 97,
    "obj2_target_pos_x": 98,
    "obj2_target_pos_y": 99,
    "obj2_target_pos_z": 100,
    "obj1_target_rot_x": 101,  # Generic object rotation, e.g., for reorient and pen
    "obj1_target_rot_y": 102,
    "obj1_target_rot_z": 103,
    "die": 104,  # reorient object
    "addbrev_r": 105,  # legs muscles
    "addlong_r": 106,
    "addmagDist_r": 107,
    "addmagIsch_r": 108,
    "addmagMid_r": 109,
    "addmagProx_r": 110,
    "bflh_r": 111,
    "bfsh_r": 112,
    "edl_r": 113,
    "ehl_r": 114,
    "fdl_r": 115,
    "fhl_r": 116,
    "gaslat_r": 117,
    "gasmed_r": 118,
    "glmax1_r": 119,
    "glmax2_r": 120,
    "glmax3_r": 121,
    "glmed1_r": 122,
    "glmed2_r": 123,
    "glmed3_r": 124,
    "glmin1_r": 125,
    "glmin2_r": 126,
    "glmin3_r": 127,
    "grac_r": 128,
    "iliacus_r": 129,
    "perbrev_r": 130,
    "perlong_r": 131,
    "piri_r": 132,
    "psoas_r": 133,
    "recfem_r": 134,
    "sart_r": 135,
    "semimem_r": 136,
    "semiten_r": 137,
    "soleus_r": 138,
    "tfl_r": 139,
    "tibant_r": 140,
    "tibpost_r": 141,
    "vasint_r": 142,
    "vaslat_r": 143,
    "vasmed_r": 144,
    "addbrev_l": 145,
    "addlong_l": 146,
    "addmagDist_l": 147,
    "addmagIsch_l": 148,
    "addmagMid_l": 149,
    "addmagProx_l": 150,
    "bflh_l": 151,
    "bfsh_l": 152,
    "edl_l": 153,
    "ehl_l": 154,
    "fdl_l": 155,
    "fhl_l": 156,
    "gaslat_l": 157,
    "gasmed_l": 158,
    "glmax1_l": 159,
    "glmax2_l": 160,
    "glmax3_l": 161,
    "glmed1_l": 162,
    "glmed2_l": 163,
    "glmed3_l": 164,
    "glmin1_l": 165,
    "glmin2_l": 166,
    "glmin3_l": 167,
    "grac_l": 168,
    "iliacus_l": 169,
    "perbrev_l": 170,
    "perlong_l": 171,
    "piri_l": 172,
    "psoas_l": 173,
    "recfem_l": 174,
    "sart_l": 175,
    "semimem_l": 176,
    "semiten_l": 177,
    "soleus_l": 178,
    "tfl_l": 179,
    "tibant_l": 180,
    "tibpost_l": 181,
    "vasint_l": 182,
    "vaslat_l": 183,
    "vasmed_l": 184,
    "pelvis_x": 185,  # legs reach target
    "pelvis_y": 186,
    "pelvis_z": 187,
}
